baseURL = 'http://gwcoffey.com/'
languageCode = 'en-us'
title = 'gwcoffey.com'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
	navMenus = [ "Writing", "Projects", "About" ]