[build]
  command = "bin/build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.110.0"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "/.netlify/functions/webfinger"
  status = 200

[dev]
  framework = "hugo"

[functions.sitesearch]
  included_files = ["search-index/**.*", "documents.json"]
