[build]
  command = "bin/build"
  publish = "hugo/public"

[build.environment]
  HUGO_VERSION = "0.111.3"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "/.netlify/functions/webfinger"
  status = 200

[dev]
  framework = "hugo"
  command = "hugo server -s hugo/ -w"
  publish = "hugo/public"

[functions.sitesearch]
  included_files = ["netlify/functions/sitesearch/search-index/*", "netlify/functions/sitesearch/documents.json"]
