name = "gwcoffey"
license = "MIT"
description = "custom theme for gwcoffey.com -- not recommended for other use"
homepage = "https://gwcoffey.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Geoff Coffey"
  homepage = "https://gwcoffey.com/"
